### PR TITLE
0.3.10

### PR DESCRIPTION
**Pull request by doko-desuka**
@mkody I refactored some parts that were asking for it (from before your latest PR, it's things I learned about Kodi). This allowed for one less module import, for example.  

I also changed some cosmetics / UX things, like the subtitles dialog:  
ctoonSubtitleDialog

### CODE REVIEW

**Comment by doko-desuka** [comment]
I realize I should've called it 0.3.11 heh.

**Comment by mkody** [comment]
Looks good
I noticed tho that the quality selector is not in the right order now?
image

**Comment by doko-desuka** [comment]
Ah yes, I did this on purpose:  
https://github.com/doko-desuka/plugin.video.ctoonkodi/blob/2603fcb1a4c1bd2f8ac52974324ea10a3c79609b/Lib/Plugin.py#L256

Lots of people use this add-on for their kids, which don't really care about quality I believe. So to spare the servers I put the medium sizes first to make them more likely to be chosen (I think I saw this order in your embedded player some time ago).  
Would you like to show the biggest sources first?

**Comment by mkody** [comment]
Ah yeah, the reason for this order in the on the website is for browsers who can't load the player (like Internet Explorer) and I've decided 480p would be the default choice for people who then can't select the quality and this is a good choice for people with low internet speeds (like on 3G) and low specs.

**Comment by doko-desuka** [comment]
Okay, when in doubt, let the user decide. I'll add a setting to set that order:
ctoonKodiQualityOrder

**Pull request merged**
